monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*"
        alsa.card_name = "PocketMICRO2"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
