monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*"
        alsa.card_name = "PocketMICRO2"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_output.*DisplayPort*"
        alsa.card_name = "PocketMICRO2"
      }
    ]
    actions = {
      update-props = {
        audio.format = "S16LE"
        steamos-arm.sink-rank = 2
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_output.*Headphones*"
        alsa.card_name = "PocketMICRO2"
      }
    ]
    actions = {
      update-props = {
        steamos-arm.sink-rank = 3
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_output.*Speaker*"
        alsa.card_name = "PocketMICRO2"
      }
    ]
    actions = {
      update-props = {
        steamos-arm.sink-rank = 1
      }
    }
  }
]
